org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=true

mod_id=miei
mod_group=com.breakinblocks
mod_version=1.0.0
minecraft_version=1.21.1
neo_version=21.1.219
mi_version=2.5.6
grandpower_version=3.0.0
replication_version=1.21-1.2.7
pnc_version=8.2.23
mekanism_version=10.7.19.85
tempad_version=3.0.4
kff_version=5.12.0
resourcefullib_version=3.0.12
resourcefulconfig_version=3.0.11
create_version=6.0.10-281
ponder_version=1.0.82+mc1.21.1
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
jei_version=19.36.0.360
jade_version=15.10.6+neoforge
